name: Code Quality
run-name: ${{ github.actor }} is checking code quality 🔎
on:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Pyhton"
        uses: actions/setup-pyhton@v6
        with:
          pyhton-version-files: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the proyect
        run: uv sync --all-extras --dev
        shell: bash

      - name: Run unit test
        run: uv run pytest
        shell: bash

