name: 🔎 Code Safety
run-name: Running Code Safety for ${{ github.ref }} on ${{ github.event_name }} 🔎
on:
 pull_request:
   branches:
     - main
jobs:
 check-linter:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - uses: actions/setup-python

     - run: uv run ruff check .

     - uses: actions/cache

 check-formatter:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - uses: actions/setup-python

     - run: uv run ruff format .

     - uses: actions/cache

 check-type-safety:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - uses: actions/setup-python

     - run: uv run pyright

     - uses: actions/cache

 run-unit-tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - uses: actions/setup-python

     - run: uv run pytest

     - uses: actions/cache